# Generated by Django 5.0.1 on 2024-01-24 00:11

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "to do": "An issue that has not been worked on.",
        "in progress": "An issue actively being worked on.",
        "done": "A completed issue.",
    }
    Status = apps.get_model("issues", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status),
    ]
